### ISSUE TITLE
Runすると、Command /bin/sh failed with exit code 133 というエラー

### ISSUE THREAD

**Issue by 5oya** [TECH-CAMP-GEEKS/swift#1]
Runすると、Command /bin/sh failed with exit code 133 エラーが起きます。
調べてもよく分からないので知っている方いれば教えてください。

**Comment by keitin** [comment]
http://stackoverflow.com/questions/13006464/how-to-fix-the-issue-command-bin-sh-failed-with-exit-code-1-in-iphone
これやってみた？

**Comment by 5oya** [comment]
@keitin ありがとうございます！

https://github.com/realm/SwiftLint/issues/169#issuecomment-153797625
これでいけました！
swiftlintのpathが通ってなかったみたいです。

**Comment by 5oya** [comment]
解決:)
