### ISSUE TITLE
遷移前のController取得方法がわからない

### ISSUE THREAD

**Issue by 5oya** [TECH-CAMP-GEEKS/swift#4]
# WHAT

self.navigationController?.previousViewControllerで遷移前のcontrollerが取得できると思ったけどできない。

**Comment by tsugitta** [comment]
ちなみに用途はなんでしょ👀

**Comment by tsugitta** [comment]
navigationController.viewControllersから参照するとか・・

**Comment by 5oya** [comment]
用途は
「新しいcontrollerで前のcontrollerが特定のcontrollerのときだけ違う処理をしたい」です！

**Comment by 5oya** [comment]
> navigationController.viewControllersから参照するとか・・

fmfm

**Comment by tsugitta** [comment]
前のcontrollerが次のcontrollerの状態を書き換えるとかが良い気がしますね
遷移してから元のViewControllerを見に行くのって少し無駄な気もしますし

``` swift
let nextViewController = NextViewController
nextViewController.foo = bar
navigationController!.pushViewController(nextViewController)
```

**Comment by 5oya** [comment]
なるほど。ありがとうございます！！

今回は使えなかったんですけど、勉強になりました🙋🏻
